version: '3'
services:
    app:
        env_file:
            - .env
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: app
        volumes:
            - ./:/var/www/html
        networks:
            - laravel-network

    mysql-db:
        image: mysql:latest
        container_name: mysql-db
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "${DB_PORT}:${DB_PORT}"
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - laravel-network

    nginx:
        image: nginx:stable-alpine
        user: root
        container_name: nginx
        ports:
            - "${NGINX_PORT:-8080}:${NGINX_DOCKER_PORT:-443}"
        volumes:
            - ./:/var/www/html
            - ${NGINX_CONFIG_LOCAL_PATH}:${NGINX_CONFIG_DOCKER_PATH}
        networks:
            - laravel-network
networks:
    laravel-network:
        driver: bridge

volumes:
    mysql-data:
